[package]
name = "fil-deal-ingester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
env_logger = "0.11.7"
json-event-parser = "0.2.2"
log = "0.4.26"
zstd = "0.13.3"
