# fly.toml app configuration file generated for build-retrieval-tasks on 2023-12-07T09:36:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "build-retrieval-tasks"
primary_region = "cdg"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[env]
SENTRY_ENVIRONMENT = "production"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 0

[[http_service.checks]]
grace_period = "1s"
interval = "10s"
method = "GET"
timeout = "1s"
path = "/health"
